# Generated by Django 4.2.2 on 2023-06-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='envios_emails',
            field=models.ManyToManyField(null=True, to='polls.enviosemails'),
        ),
    ]
