# Generated by Django 4.2.2 on 2023-06-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_usuario_envios_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='envios_emails',
            field=models.ManyToManyField(blank=True, to='polls.enviosemails'),
        ),
    ]
