# Generated by Django 4.2.2 on 2023-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_usuario_envios_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='envios_emails',
        ),
        migrations.AddField(
            model_name='enviosemails',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, to='polls.usuario'),
        ),
    ]
